<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 .\untitled.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('untitled-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0.45, 0.02, -0.02]}>
      <T.Mesh geometry={gltf.nodes.wp01a_attach001c_smmd.geometry} material={gltf.materials.wp01a_attach001c_inst} />
      <T.Mesh geometry={gltf.nodes.wp01a_attach001c_smmd_1.geometry} material={gltf.materials.wp01a_a001c_inst2} />
    </T.Group>
    <T.Group position={[0.22, 0, 0.02]} rotation={[0, -0.35, 0]}>
      <T.Mesh
        geometry={gltf.nodes.wp01a_magazine001c_smmd.geometry}
        material={gltf.materials.wp01a_magazine001c_inst}
      />
      <T.Mesh geometry={gltf.nodes.wp01a_magazine001c_smmd_1.geometry} material={gltf.materials.wp01a_a001c_inst2} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.wp01a_muzzle001c_smmo.geometry}
      material={gltf.materials.wp01a_muzzle001c_inst}
      position={[0.58, 0, -0.02]}
    />
    <T.Group position={[0.12, 0, -0.05]}>
      <T.Mesh geometry={gltf.nodes.wp01a_scope001c_smmd.geometry} material={gltf.materials.wp01a_scope001c_inst} />
      <T.Mesh geometry={gltf.nodes.wp01a_scope001c_smmd_1.geometry} material={gltf.materials.wp01a_a001c_inst2} />
    </T.Group>
    <T.Mesh geometry={gltf.nodes.wp01a_a001c_smmd.geometry} material={gltf.materials.wp01a_a001c_inst} />
    <T.Mesh geometry={gltf.nodes.wp01a_a001c_smmd_1.geometry} material={gltf.materials.wp01a_a001c_inst2} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
