<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 -T .\flour.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('models/flour-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[Math.PI / 2, 0, 0]} scale={[1.66, 1.66, 1.86]}>
      <T.Mesh geometry={gltf.nodes.Cube003.geometry} material={gltf.materials['Material.003']} />
      <T.Mesh geometry={gltf.nodes.Cube003_1.geometry} material={gltf.materials['Material.002']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
