<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 -T .\sugar.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('models/sugar-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={[1.33, 0.12, 1.33]}>
      <T.Mesh geometry={gltf.nodes.Cylinder001_1.geometry} material={gltf.materials['Material.005']} />
      <T.Mesh geometry={gltf.nodes.Cylinder001_2.geometry} material={gltf.materials['Material.004']} />
      <T.Mesh geometry={gltf.nodes.Cylinder001_3.geometry} material={gltf.materials['Material.006']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
